### ISSUE TITLE
Bad HREF - Data Analytics

### ISSUE THREAD

**Issue by EdFabre** [EdFabre/Joint-Program-Site#1]
It has been brought to our attention that the data analytics redirect was not configured in IIS, so Ed took care of it. Also Under Our **Programs>Professional Development** the _"Executive Program in
Applied Data Analytics"_ link is broken.

![capture](https://cloud.githubusercontent.com/assets/9345618/21432373/3f3bb00e-c839-11e6-97b6-b44e77283e07.PNG)

**Comment by vulpcod3z** [comment]
Awesome @EdFabre Sleepiness does that to ya..

**Comment by vulpcod3z** [comment]
Href value changed to 'http://dataanalytics.umd.edu/'
- Fixed

**Comment by EdFabre** [comment]
I leave it to you xD
